app = "t1nylinks"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = "80"

  [[services.ports]]
    port = "443"

  [[services.https_checks]]
    hostname = "t1nylinks.fly.dev"

